### ISSUE TITLE
KlarnaMobileiOSSDK is 6MB. Framework size is way bigger than expected for a payment library. 

### ISSUE THREAD

**Issue by arturonaredo** [klarna/klarna-mobile-sdk#217]
Hey there, 

after analizyng the size of my app I noticed that KlarnaSDK for iOS is 6.1MB. This is a big oversized for a payment library isn't? Other libraries like Cardinal are around 900Kb. 

could you please review the size of your framework? 

We are on version 2.6.8. 

<img width="426" alt="Captura de pantalla 2023-11-02 a las 13 22 56" src="https://github.com/klarna/klarna-mobile-sdk/assets/714159/c4611b38-9990-498d-8180-9aa5b79824de">

<img width="308" alt="Captura de pantalla 2023-11-02 a las 13 27 29" src="https://github.com/klarna/klarna-mobile-sdk/assets/714159/5e53f98e-4e9f-4e74-9fff-17190ce788b0">

Thanks for considering.

**Comment by arturonaredo** [comment]
Hello?

Why you are adding models for inference lines and boxes on your standard flavor library?

**Comment by NMGuner** [comment]
Hi @arturonaredo, we changed the default variant/subspec, hence it's significantly smaller now. We can see 3MB decrease in download size of the app once built with the SDK. Framework size you are observing here is also down to 2.7MB instead of 6.1MB you got.

Please update your integration to the latest version and let us know if you still have concerns regarding the size of the library.
