### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by MKGitHub** [klarna/klarna-mobile-sdk#7]
Analyse the binary.
Your name appears thousands of times along with a whole bunch of interesting info from your machine.

**Comment by gbanfalvikl** [comment]
Good catch! I just took a quick glance, and it seems to happen in several other Swift binary frameworks too, but the weird part is that it only exposes specific file paths – so at least on the surface, it doesn't seem like a it's a misapplied build setting. 

Any idea what could be causing this?

**Comment by gbanfalvikl** [comment]
We found the cause of the issue!  It's caused by a code coverage flag that is by default on release builds. 

We've had some internal discussions and decided that it's a relatively low-prioissue. We already provide merchants with dSYMs and bitcode symbol maps which expose most (if not all) of the SDK's 
structure and private identifiers. The file paths with usernames in the binaries by themselves don't constitute a security threat. 

We'll be fixing this in a future release once we update some of of our CI process.

Thanks for reporting.

**Comment by breferrari** [comment]
Hi 👋 
Is this issue fixed in the latest release? We use the SDK on our app and we're getting errors in the `lldb` that points paths with your usernames.
This is blocking us to use the `lldb` to properly debug our app. We can't even do a simple `po` command.

```
error: virtual filesystem overlay file '/Users/carlos.jimenez/Library/Developer/Xcode/DerivedData/KlarnaMobileSDK-bfjfbshljhpqyrbnhsmaiszqmfat/Build/Intermediates.noindex/KlarnaMobileSDK.build/Release-iphonesimulator/KlarnaMobileSDK.build/all-product-headers.yaml' not found
error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```
